### ISSUE TITLE
Missing labels on plots

### ISSUE THREAD

**Issue by blastmaster** [wangvsa/recorder-viz#1] opened 2022-08-17 15:10 UTC
Hi, 
When using recorder-viz I've the problem that the Plots 2.3, 2.4 and 4.2 does not have any labels. 
I attached a picture, is it just me? Maybe not having the right fonts installed? 
Did you have any hints for me on that?
Thanks

![recorder-viz-function-count](https://user-images.githubusercontent.com/1430740/185175017-1700ab1d-e0ca-4be8-b5b8-3bf36dc91fe0.png)

**Comment by blastmaster** [comment] 2022-08-17 15:11
The other plots does have labels ... so this might not be a font issue.

**Comment by wangvsa** [comment] 2022-08-17 15:27
That is strange. I just did a quick test and the plots are showing fine. Is there a way for me to reproduce the issue? Probably send over the traces so I can test on my side if that's ok?

**Comment by blastmaster** [comment] 2022-08-18 11:13
Hi, I sent you an email to your university address containing a download link for the trace file.

**Comment by wangvsa** [comment] 2022-08-18 15:58
Got your traces. It shows fine on my side though, just the generated html is huge (~500MB)
![image](https://user-images.githubusercontent.com/2760209/185440691-585361a1-b5f1-4e5e-96e1-64f6172a23f8.png)
Can you try with some smaller traces to see if the issue still exist?

**Comment by roblatham00** [comment] 2022-09-12 19:37
I'm observing the same problem

![image](https://user-images.githubusercontent.com/2278417/189737558-fd6f37e9-9430-4578-89ca-980fcf9ee805.png)

but in my case the trace is pretty small --- 96k according to 'du'

**Comment by wangvsa** [comment] 2022-09-12 22:54
This seems to be a bokeh version issue. It only happens to the latest bokeh-2.4.3, older versions work fine. I am trying to see what exactly caused the problem.

**Comment by wangvsa** [comment] 2022-09-13 15:55
I believe I have fixed the issue, please update recorder_viz to the latest version (0.4.5) and give it a try.
`
pip3 install recorder_viz --upgrade
`

**Comment by roblatham00** [comment] 2022-09-13 18:49
Fantastic! with this update yes, I see the expected labels on 2.3 and 24

**Comment by wangvsa** [comment] 2022-09-14 01:13
Great! I'll close the issue then. @blastmaster let me know if you still have the issue.

**Closed by wangvsa** 2022-09-14 01:13 UTC
